spring:
  application:
    name: carrive-passenger
  data:
    mongodb:
      database: carrive_db
      host: localhost
      port: 27017
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
server:
  port: 8087